### ISSUE TITLE
Always "Not ready" status in openfaas dashboard

### ISSUE THREAD

**Issue by naturlich** [s8sg/faas-flow#119]
Hi,

I  tried to run the greet example, but the status always shows "Not ready".
Are the ymls and setting correct?
Thanks.

My greet.yml is <br>
```
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  greet:
    lang: faas-flow
    handler: ./greet
    image: greet:latest
    environment:
      read_timeout: 120 # A value larger than `max` of all execution times of Nodes
      write_timeout: 120 # A value larger than `max` of all execution times of Nodes
      exec_timeout: 0 # disable exec timeout
      write_debug: true
      combine_output: false
    environment_file:
      - flow.yml
```
The flow.yml is
```
environment:
  gateway: http://127.0.0.1:31112 # The address of OpenFaaS gateway, Faas-flow use this to forward completion event
  enable_tracing: false # tracing allow to trace internal node execution with opentracing
  enable_hmac: true # hmac adds an extra layer of security by validating the event source
```
The result is
![image](https://user-images.githubusercontent.com/12527233/67564085-c0794f80-f754-11e9-9572-9f3f4fae2f4a.png)
