### ISSUE TITLE
Make Consul and Minio as default StateStore and DataStore 

### ISSUE THREAD

**Issue by s8sg** [s8sg/faas-flow#137]
FaasFlow needs StateStore and DataStore to operate with all the feature
We are making the  `StateStore` and `DataStore` mandatory for Faas-flow to operate and this configuration must be provided with flow configuration 

## Consul as default StateStore
Faas flow will use `Consul` as the default state Store 
We already have a `ConsulStateStore` implementation (https://github.com/s8sg/faas-flow-consul-statestore)

The flow need to be configured with the configuration to connect to consul 
```yaml
consul_url: "consul.faasflow:8500"
consul_dc: "dc1"
```

## Minio as default DataStore
Faas flow will use `Minio` as the default Data Store 
We already have a `MinioDataStore` implementation (https://github.com/s8sg/faas-flow-minio-datastore)

The flow need to be configured with the configuration to connect to Minio/s3
```yaml
      s3_url: "minio.faasflow:9000"
      s3_tls: false
      s3_secret_key_name: "s3-secret-key"
      s3_access_key_name: "s3-access-key"
    secrets:
      - s3-secret-key
      - s3-access-key
```

## Override `StateStore` and `DataStore`
User still can override the `StateStore` and `DataStore`. ProvideStateStore and ProvideDataStore function will be changed to OverrideStateStore and OverrideStateStore.

## Update Readme 
Readme needs to be updated so reflect the above changes and to ensure the documentation is aligned on the below point:
1. FaaSFlow infra is necessary for Faas-flow to operate 
2. Describe how to change configuration to connect with the default StateStore and DataStore
3. Update the part where StateStore and DataStore definition example is provided
