### ISSUE TITLE
faas build the demo case yml failed

### ISSUE THREAD

**Issue by heavenlxj** [s8sg/faas-flow#149]
following the demo case,   use default greet template the faas build could be worked for me, but if I add the environment_file and secrets part, faas build will be failed with the below error:

```
liudeMacBook-Pro-2:faas xjliu$ faas build -f greet.yml
Error with YAML file
Yaml: unmarshal errors:
  line 15: cannot unmarshal !!seq into stack.Function
  line 17: cannot unmarshal !!seq into stack.Function
```

the greet.yml pasted here:
```
version: 1.0
provider:
  name: openfaas
  gateway: http://10.100.121.9:31112
functions:
  greet:
    lang: faas-flow
    handler: ./greet
    image: docker.4pd.io/apache/openfaas/functions/greet:latest
  labels:
    faas-flow: 1
  annotations:
    faas-flow-desc: "test flow to greet"
  environment_file:
    - flow.yml
  secrets:
    - s3-secret-key
    - s3-access-key
```

and the flow.yml is same as the demo case. 
i found no related issue about this, anyone knows what's wrong with this? thanks
